services:
  # Data sources
  mysql:

  mongodb:

  # Lakehouse storage
  namenode: 

  datanode:

  # Ingestion Layer
  kafka: 

  kafka-connect:

  # Processing Layer
  flink:

  # Mart Layer
  clickhouse:

  # Query Engine
  trino:

  # Visualize Layer
  superset:

networks:
  streamhouse:
    driver: bridge